# Generated by Django 3.2.6 on 2021-10-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211023_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='jewellery_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
